name: SwiftFormat

on:
  pull_request

jobs:
  format:
    runs-on: macos-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: debug
        run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_HEAD_REF}
          echo ${GITHUB_REF_NAME}
          echo $(git branch)
          echo $(git status)

      - uses: irgaly/setup-mint@v1

      - name: execute swift-format
        run: mint run swift-format swift-format format --recursive --in-place .

      - name: git push
        run: |
          git config --local user.email "github.actions@example.com"
          git config --local user.name "github actions"
          git add "*.swift"
          git commit -m "Execute swift-format" && git push
